version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  authentication:
    image: fabiobufalari/authentication:latest
    container_name: authentication
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Ajuste conforme sua imagem/auth config
    depends_on:
      - postgres

  company:
    build:
      context: .
    container_name: company
    restart: always
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      AUTH_SERVER_JWK_URL: http://authentication:8083/.well-known/jwks.json
    depends_on:
      - postgres
      - authentication
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
