# =========================================
# Server Configuration
# =========================================
server:
  port: 8082 # <<< Porta Exemplo para este serviço

# =========================================
# Spring Boot Application Configuration
# =========================================
spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://localhost:5432/buildingDB # <<< BANCO CENTRALIZADO
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages: # Configuração i18n (se mantida)
    basename: messages # Verificar caminho exato do arquivo messages.properties
    encoding: UTF-8
    fallback-to-system-locale: false

# =========================================
# JWT Configuration (Este serviço VALIDA) - Ajustado para o padrão
# =========================================
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970!} # <<< CHAVE IDÊNTICA
# Remover config antiga de oauth2/resourceserver se não for mais usada
#  oauth2:
#    resourceserver:
#      jwt:
#        secret: ${JWT_SECRET:umaSenhaMuitoSeguraParaJWT123456!} # Removido/Comentado

# =========================================
# Logging Configuration
# =========================================
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bufalari.company: DEBUG # Pacote raiz deste serviço
    org.hibernate.SQL: DEBUG

# =========================================
# Swagger/OpenAPI Configuration
# =========================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# =========================================
# Actuator Configuration
# =========================================
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized

auth: # <<< Nível raiz
  service: # <<< Nível 2
    url: ${AUTH_SERVICE_URL:http://localhost:8083/api} # <<< Nível 3