# =========================================
# MS company
# =========================================

# =========================================
# Server Configuration
# =========================================
server:
  port: 8079 # <<< Porta Exemplo para este serviço
  servlet:
    context-path: /api # <<< MANTIDO O CONTEXT PATH /api

# =========================================
# Spring Boot Application Configuration
# =========================================
spring:
  application:
    name: company-service
  datasource:
    url: ${DATASOURCE_URL} # <<< BANCO CENTRALIZADO
    username: ${DATASOURCE_USERNAME_PROD}
    password: ${DATASOURCE_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  messages: # Configuração i18n (se mantida)
    basename: messages # Verificar caminho exato do arquivo messages.properties
    encoding: UTF-8
    fallback-to-system-locale: false

# =========================================
# JWT Configuration (Este serviço VALIDA) - Ajustado para o padrão
# =========================================
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY} # <<< CHAVE IDÊNTICA

# =========================================
# Logging Configuration
# =========================================
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bufalari.company: DEBUG # Pacote raiz deste serviço
    org.hibernate.SQL: DEBUG

# =========================================
# Swagger/OpenAPI Configuration
# =========================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# =========================================
# Actuator Configuration
# =========================================
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized

auth: # <<< Nível raiz
  service: # <<< Nível 2
    url: ${AUTH_SERVICE_URL} # <<< Nível 3
    #url: ${AUTH_SERVICE_URL:http://localhost:8083/api} # <<< Nível 3